sudo: false
language: node_js
node_js:
  - "4"
  - "6"
script:
  - npm run ci
after_script:
  - npm run report-coverage
notifications:
  slack:
    secure: qhKaWMxnys3BXMIzu8+MkKO1ucXO41HkjLAut09dCbOzRcmfkPLS5LO9FW9H5Or1PG2ALQQoStivyzuqpu+Jsw9StxxyGbG7FaZcCMB6RjuGI5UcXzHxpA9J8Ukq6DQBkru6hXplgP8Ma1ZBciuYHrKcuBrF2a6Fc8qXRqR0Nlk=
